import NavList from "./components/NavList";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Any Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-primary flex">
          <NavList />
          <div className="min-h-screen flex container mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
